#!/usr/bin/zsh

NEW_BANDIT=bandit$1
OLD_BANDIT=bandit$(($1-1))
BANDIT_STRING="BANDIT = $(($1-1))"

mkdir $NEW_BANDIT
cp $OLD_BANDIT/$OLD_BANDIT.py $NEW_BANDIT/$NEW_BANDIT.py
sed -i "s/$BANDIT_STRING/BANDIT = $1/" $NEW_BANDIT/$NEW_BANDIT.py
sed -i "s/payload\ =.*/payload = \"\/bin\/echo \\\\\"Edit the payload string in $NEW_BANDIT.py\\\\\"\"/" $NEW_BANDIT/$NEW_BANDIT.py
#echo $NEW_BANDIT
#echo $OLD_BANDIT
